GET http://localhost:3000/orders

POST http://localhost:3000/orders HTTP/1.1
content-type: application/json

{
	"items": [{
			"id": "5YPO1Smo3mcMoqkMcGOK0W",
			"amount": "1",
			"colorId": "4Cjuek1kdqgGswW0iOwawc",
      "fraganceId": "52fomcNjNKAimUeOuM2QOq"
		},
		{
			"id": "69sC7kthhSEkYscyQu8WEQ",
			"amount": "2",
			"colorId": "592DUMfwiQQ64egUsOOaI4",
      "fraganceId": "52fomcNjNKAimUeOuM2QOq"
		}
	]
}